_meta:
  var:
  - id
  - Chapter
  - Loop
  - SceneID
  - TaskID
  type:
  - string
  - int
  - int
  - string
  - string
  desc:
  - 游戏状态ID
  - 所属章节
  - 所属循环
  - 可访问场景ID
  - 任务ID
data:
- id: CC11
  Chapter: 1
  Loop: 1
  SceneID: SC1001/SC1002/SC1003/SC1010
  TaskID: Task11
- id: CC12
  Chapter: 1
  Loop: 2
  SceneID: SC1001/SC1003/SC1010/SC1005/SC1006/SC1004/SC1007/SC1018
  TaskID: Task12
- id: CC13
  Chapter: 1
  Loop: 3
  SceneID: SC1008/SC1003/SC1009/SC1007/SC1001/SC1010
  TaskID: Task13
- id: CC14
  Chapter: 1
  Loop: 4
  SceneID: SC1011/SC1012/SC1013/SC1003/SC1007/SC1001/SC1010/SC1008
  TaskID: Task14
- id: CC15
  Chapter: 1
  Loop: 5
  SceneID: SC1007/SC1009/SC1003/SC1001/SC1010/SC1011/SC1008
  TaskID: Task15
- id: CC16
  Chapter: 1
  Loop: 6
  SceneID: SC1004/SC1009/SC1011/SC1001/SC1007/SC1003/SC1008
  TaskID: Task16
