_meta:
  var:
  - sceneId
  - sectionId
  - sceneName
  - sceneNameEn
  - chapterId
  - sceneType
  - backgroundImage
  - backgroundMusic
  - ambientSound
  - unlockCondition
  - npcsPresent
  - 备注
  type:
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  desc:
  - 场景ID
  - 小节ID
  - 中文场景名
  - 英文场景名
  - 章节ID
  - 场景类型
  - 背景图路径
  - 背景音乐
  - 环境音效
  - 解锁条件
  - 场景NPC
  - 备注
data:
- sceneId: SC1001
  sectionId: ''
  sceneName: Rosa储藏室
  sceneNameEn: RosaStorageRoom
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC001_bg_RosaStorageRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 酒吧后方的储藏室，堆满杂物，是Rosa的私人空间
- sceneId: SC1002
  sectionId: ''
  sceneName: 歌舞厅一楼走廊
  sceneNameEn: CabaretFirstFloorCorridor
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC002_bg_CabaretFirstFloorCorridor.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 案发现场附近的走廊，空旷安静
- sceneId: SC1003
  sectionId: ''
  sceneName: Tommy办公室
  sceneNameEn: TommyOffice
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC003_bg_TommyOffice.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 酒吧经理Tommy的办公室，堆满账本和文件
- sceneId: SC1004
  sectionId: ''
  sceneName: Webb会客室
  sceneNameEn: WebbReceptionRoom
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC004_bg_WebbReceptionRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Webb生前用于接待客人的会客室
- sceneId: SC1005
  sectionId: ''
  sceneName: Morrison家客厅
  sceneNameEn: MorrisonHomeLivingRoom
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC005_bg_MorrisonHomeLivingRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Morrison警官的家中客厅，布置简朴
- sceneId: SC1006
  sectionId: ''
  sceneName: Morrison家书房
  sceneNameEn: MorrisonHomeStudy
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC006_bg_MorrisonHomeStudy.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Morrison警官的书房，隐藏着许多秘密
- sceneId: SC1007
  sectionId: ''
  sceneName: Vivian化妆室
  sceneNameEn: VivianDressingRoom
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC007_bg_VivianDressingRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 歌舞厅头牌Vivian的私人化妆室，充满女性气息
- sceneId: SC1008
  sectionId: ''
  sceneName: Webb办公室
  sceneNameEn: WebbOffice
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC008_bg_WebbOffice.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Webb的私人办公室，案发现场
- sceneId: SC1009
  sectionId: ''
  sceneName: 酒吧歌舞厅
  sceneNameEn: BarCabaret
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC009_bg_BarCabaret.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 蓝月亮歌舞厅的表演大厅，舞台灯光璀璨
- sceneId: SC1010
  sectionId: ''
  sceneName: 酒吧大堂
  sceneNameEn: BarLobby
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC010_bg_BarLobby.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 蓝月亮歌舞厅的主大堂，装潢华丽
- sceneId: SC1011
  sectionId: ''
  sceneName: Jimmy厨房
  sceneNameEn: JimmyKitchen
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC011_bg_JimmyKitchen.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 酒吧后厨，Jimmy工作的地方
- sceneId: SC1012
  sectionId: ''
  sceneName: Jimmy家卧室
  sceneNameEn: JimmyHomeBedroom
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC012_bg_JimmyHomeBedroom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Jimmy的住所卧室，简陋但整洁
- sceneId: SC1013
  sectionId: ''
  sceneName: 酒吧外街道
  sceneNameEn: BarStreet
  chapterId: ''
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC013_bg_BarStreet.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 蓝月亮歌舞厅外的街道，夜色昏暗，路灯微弱
