_meta:
  var:
  - sceneId
  - sceneName
  - sceneNameEn
  - sceneType
  - backgroundImage
  - backgroundMusic
  - ambientSound
  - unlockCondition
  - npcsPresent
  - 备注
  type:
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  - string
  desc:
  - 场景ID
  - 中文场景名
  - 英文场景名
  - 场景类型
  - 背景图路径
  - 背景音乐
  - 环境音效
  - 解锁条件
  - 场景NPC
  - 备注
data:
- sceneId: SC1001
  sceneName: Rosa储藏室
  sceneNameEn: RosaStorageRoom
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC001_bg_RosaStorageRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 酒吧后方的储藏室，堆满杂物，是Rosa的私人空间
- sceneId: SC1002
  sceneName: 歌舞厅一楼走廊
  sceneNameEn: CabaretFirstFloorCorridor
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC002_bg_CabaretFirstFloorCorridor.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 案发现场附近的走廊，空旷安静
- sceneId: SC1003
  sceneName: Tommy办公室
  sceneNameEn: TommyOffice
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC003_bg_TommyOffice.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 酒吧经理Tommy的办公室，堆满账本和文件
- sceneId: SC1004
  sceneName: Webb会客室
  sceneNameEn: WebbReceptionRoom
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC004_bg_WebbReceptionRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Webb生前用于接待客人的会客室
- sceneId: SC1005
  sceneName: Morrison家客厅
  sceneNameEn: MorrisonHomeLivingRoom
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC005_bg_MorrisonHomeLivingRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Morrison警官的家中客厅，布置简朴
- sceneId: SC1006
  sceneName: Morrison家书房
  sceneNameEn: MorrisonHomeStudy
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC006_bg_MorrisonHomeStudy.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Morrison警官的书房，隐藏着许多秘密
- sceneId: SC1007
  sceneName: Vivian化妆室
  sceneNameEn: VivianDressingRoom
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC007_bg_VivianDressingRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 歌舞厅头牌Vivian的私人化妆室，充满女性气息
- sceneId: SC1008
  sceneName: Webb办公室
  sceneNameEn: WebbOffice
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC008_bg_WebbOffice.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Webb的私人办公室，案发现场
- sceneId: SC1009
  sceneName: 酒吧歌舞厅
  sceneNameEn: BarCabaret
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC009_bg_BarCabaret.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 蓝月亮歌舞厅的表演大厅，舞台灯光璀璨
- sceneId: SC1010
  sceneName: 酒吧大堂
  sceneNameEn: BarLobby
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC010_bg_BarLobby.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 蓝月亮歌舞厅的主大堂，装潢华丽
- sceneId: SC1011
  sceneName: Jimmy厨房
  sceneNameEn: JimmyKitchen
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC011_bg_JimmyKitchen.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 酒吧后厨，Jimmy工作的地方
- sceneId: SC1012
  sceneName: Jimmy家卧室
  sceneNameEn: JimmyHomeBedroom
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC012_bg_JimmyHomeBedroom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Jimmy的住所卧室，简陋但整洁
- sceneId: SC1013
  sceneName: Jimmy家客厅
  sceneNameEn: JimmyHomeLivingRoom
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC013_bg_JimmyHomeLivingRoom.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: Jimmy的住所客厅
- sceneId: SC1014
  sceneName: 歌舞厅二楼走廊
  sceneNameEn: CabaretSecondFloorCorridor
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC014_bg_CabaretSecondFloorCorridor.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 歌舞厅二楼的走廊
- sceneId: SC1015
  sceneName: 歌舞厅地下室走廊
  sceneNameEn: CabaretBasementCorridor
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC015_bg_CabaretBasementCorridor.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 歌舞厅地下室的走廊
- sceneId: SC1016
  sceneName: 厨房走廊
  sceneNameEn: KitchenCorridor
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC016_bg_kitchenCorridor.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 通往厨房的走廊
- sceneId: SC1017
  sceneName: 酒吧外街道
  sceneNameEn: BarStreet
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC017_bg_BarStreet.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 蓝月亮歌舞厅外的街道，夜色昏暗，路灯微弱
- sceneId: SC1018
  sceneName: Morrison办公室
  sceneNameEn: MorrisonOffice
  sceneType: dialogue
  backgroundImage: Art/Scenes/SC018_bg_MorrisonOffice.png
  backgroundMusic: ''
  ambientSound: ''
  unlockCondition: ''
  npcsPresent: ''
  备注: 芝加哥警局Morrison警探的办公室
